#!/bin/bash
#PBS -q workq
#PBS -N Convert_SCZ_CC
#PBS -V 
#PBS -S /bin/bash 
#PBS -l nodes=1:ppn=6
#PBS -o convert_gen.log
#PBS -e convert_gen.err

cd $PBS_O_WORKDIR

date
# for i in {1..22}
# do
# /home/edizadehm/01.software/02.plink/plink \
#     --vcf /home/projects/IrishGWAS/SCZ_CC/Post_all_QC/HRC_version_r.1.1/vcfs/chr$i.dose.vcf.gz \
#     --recode oxford \
#     --out /home/edizadehm/03.resources/03.SCZ_CC/02.original_SCZ_CC_data/genos/SCZ_CC_chr$i \
#     --double-id 
# done

# date

# for i in {1..22}
# do
# /path/to/bcftools/bcftools convert --chrom  --vcf-ids --tag GP --gensample /home/edizadehm/03.resources/03.SCZ_CC/02.original_SCZ_CC_data/genos/SCZ_CC.chr$i /home/projects/IrishGWAS/SCZ_CC/Post_all_QC/HRC_version_r.1.1/vcfs/chr$i.dose.vcf.gz
# done

for i in {1..22}
do
/home/edizadehm/01.software/07.qctool/qctool -g /home/projects/IrishGWAS/SCZ_CC/Post_all_QC/HRC_version_r.1.1/vcfs/chr22.dose.vcf.gz -og /home/edizadehm/03.resources/03.SCZ_CC/02.original_SCZ_CC_data/genos/SCZ_CC.chr22.qctool.bgen
done 

# bgenix -g /home/edizadehm/03.resources/03.SCZ_CC/02.original_SCZ_CC_data/genos/HRC.r.1.1.chr22.gen.gz -index
# bgenix -g /home/edizadehm/03.resources/03.SCZ_CC/02.original_SCZ_CC_data/genos/SCZ_CC_chr22.gen -index