#!/bin/bash
#PBS -q workq
#PBS -N Convert22
#PBS -V 
#PBS -S /bin/bash 
#PBS -l nodes=1:ppn=6
#PBS -o convert22.log
#PBS -e convert22.err

cd $PBS_O_WORKDIR

date
# for i in {1..22}
# do
# /home/edizadehm/01.software/02.plink/plink \
#     --vcf /home/projects/IrishGWAS/SCZ_CC/Post_all_QC/HRC_version_r.1.1/vcfs/chr$i.dose.vcf.gz \
#     --recode oxford \
#     --out /home/edizadehm/03.resources/03.SCZ_CC/02.original_SCZ_CC_data/genos/SCZ_CC_chr$i \
#     --double-id 
# done

# date

# for i in {1..22}
# do
# /path/to/bcftools/bcftools convert --chrom  --vcf-ids --tag GP --gensample /home/edizadehm/03.resources/03.SCZ_CC/02.original_SCZ_CC_data/genos/SCZ_CC.chr$i /home/projects/IrishGWAS/SCZ_CC/Post_all_QC/HRC_version_r.1.1/vcfs/chr$i.dose.vcf.gz
# done
scl enable devtoolset-11 bash # it loads gcc version 11

# for i in {10..22}
# do
# /home/edizadehm/01.software/05.qctool/qctool/build/release/apps/qctool_v2.2.0 \
#     -g /home/projects/IrishGWAS/SCZ_CC/Post_all_QC/HRC_version_r.1.1/vcfs/chr${i}.dose_filtered.vcf.gz \
#     -og /home/edizadehm/03.resources/03.SCZ_CC/02.original_SCZ_CC_data/genos/chr${i}.bgen
# done

for i in {1..9}
do
/home/edizadehm/01.software/bgenix -g /home/edizadehm/03.resources/03.SCZ_CC/02.original_SCZ_CC_data/genos/chr${i}.bgen -index
done 
